authors:
  arjanvanbremen:
    name: Arjan van Bremen
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/25454736
    url: https://github.com/avanbremen
  mathijsvanbremen:
    name: Mathijs van Bremen
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/10992129
    url: https://github.com/iMvBremen